<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array(
            array('id' => '1','province_id' => '1','name' => 'Maroa','capital' => '0'),
            array('id' => '2','province_id' => '1','name' => 'Puerto Ayacucho','capital' => '1'),
            array('id' => '3','province_id' => '1','name' => 'San Fernando de Atabapo','capital' => '0'),
            array('id' => '4','province_id' => '2','name' => 'Anaco','capital' => '0'),
            array('id' => '5','province_id' => '2','name' => 'Aragua de Barcelona','capital' => '0'),
            array('id' => '6','province_id' => '2','name' => 'Barcelona','capital' => '1'),
            array('id' => '7','province_id' => '2','name' => 'Boca de Uchire','capital' => '0'),
            array('id' => '8','province_id' => '2','name' => 'Cantaura','capital' => '0'),
            array('id' => '9','province_id' => '2','name' => 'Clarines','capital' => '0'),
            array('id' => '10','province_id' => '2','name' => 'El Chaparro','capital' => '0'),
            array('id' => '11','province_id' => '2','name' => 'El Pao Anzoátegui','capital' => '0'),
            array('id' => '12','province_id' => '2','name' => 'El Tigre','capital' => '0'),
            array('id' => '13','province_id' => '2','name' => 'El Tigrito','capital' => '0'),
            array('id' => '14','province_id' => '2','name' => 'Guanape','capital' => '0'),
            array('id' => '15','province_id' => '2','name' => 'Guanta','capital' => '0'),
            array('id' => '16','province_id' => '2','name' => 'Lechería','capital' => '0'),
            array('id' => '17','province_id' => '2','name' => 'Onoto','capital' => '0'),
            array('id' => '18','province_id' => '2','name' => 'Pariaguán','capital' => '0'),
            array('id' => '19','province_id' => '2','name' => 'Píritu','capital' => '0'),
            array('id' => '20','province_id' => '2','name' => 'Puerto La Cruz','capital' => '0'),
            array('id' => '21','province_id' => '2','name' => 'Puerto Píritu','capital' => '0'),
            array('id' => '22','province_id' => '2','name' => 'Sabana de Uchire','capital' => '0'),
            array('id' => '23','province_id' => '2','name' => 'San Mateo Anzoátegui','capital' => '0'),
            array('id' => '24','province_id' => '2','name' => 'San Pablo Anzoátegui','capital' => '0'),
            array('id' => '25','province_id' => '2','name' => 'San Tomé','capital' => '0'),
            array('id' => '26','province_id' => '2','name' => 'Santa Ana de Anzoátegui','capital' => '0'),
            array('id' => '27','province_id' => '2','name' => 'Santa Fe Anzoátegui','capital' => '0'),
            array('id' => '28','province_id' => '2','name' => 'Santa Rosa','capital' => '0'),
            array('id' => '29','province_id' => '2','name' => 'Soledad','capital' => '0'),
            array('id' => '30','province_id' => '2','name' => 'Urica','capital' => '0'),
            array('id' => '31','province_id' => '2','name' => 'Valle de Guanape','capital' => '0'),
            array('id' => '43','province_id' => '3','name' => 'Achaguas','capital' => '0'),
            array('id' => '44','province_id' => '3','name' => 'Biruaca','capital' => '0'),
            array('id' => '45','province_id' => '3','name' => 'Bruzual','capital' => '0'),
            array('id' => '46','province_id' => '3','name' => 'El Amparo','capital' => '0'),
            array('id' => '47','province_id' => '3','name' => 'El Nula','capital' => '0'),
            array('id' => '48','province_id' => '3','name' => 'Elorza','capital' => '0'),
            array('id' => '49','province_id' => '3','name' => 'Guasdualito','capital' => '0'),
            array('id' => '50','province_id' => '3','name' => 'Mantecal','capital' => '0'),
            array('id' => '51','province_id' => '3','name' => 'Puerto Páez','capital' => '0'),
            array('id' => '52','province_id' => '3','name' => 'San Fernando de Apure','capital' => '1'),
            array('id' => '53','province_id' => '3','name' => 'San Juan de Payara','capital' => '0'),
            array('id' => '54','province_id' => '4','name' => 'Barbacoas','capital' => '0'),
            array('id' => '55','province_id' => '4','name' => 'Cagua','capital' => '0'),
            array('id' => '56','province_id' => '4','name' => 'Camatagua','capital' => '0'),
            array('id' => '58','province_id' => '4','name' => 'Choroní','capital' => '0'),
            array('id' => '59','province_id' => '4','name' => 'Colonia Tovar','capital' => '0'),
            array('id' => '60','province_id' => '4','name' => 'El Consejo','capital' => '0'),
            array('id' => '61','province_id' => '4','name' => 'La Victoria','capital' => '0'),
            array('id' => '62','province_id' => '4','name' => 'Las Tejerías','capital' => '0'),
            array('id' => '63','province_id' => '4','name' => 'Magdaleno','capital' => '0'),
            array('id' => '64','province_id' => '4','name' => 'Maracay','capital' => '1'),
            array('id' => '65','province_id' => '4','name' => 'Ocumare de La Costa','capital' => '0'),
            array('id' => '66','province_id' => '4','name' => 'Palo Negro','capital' => '0'),
            array('id' => '67','province_id' => '4','name' => 'San Casimiro','capital' => '0'),
            array('id' => '68','province_id' => '4','name' => 'San Mateo','capital' => '0'),
            array('id' => '69','province_id' => '4','name' => 'San Sebastián','capital' => '0'),
            array('id' => '70','province_id' => '4','name' => 'Santa Cruz de Aragua','capital' => '0'),
            array('id' => '71','province_id' => '4','name' => 'Tocorón','capital' => '0'),
            array('id' => '72','province_id' => '4','name' => 'Turmero','capital' => '0'),
            array('id' => '73','province_id' => '4','name' => 'Villa de Cura','capital' => '0'),
            array('id' => '74','province_id' => '4','name' => 'Zuata','capital' => '0'),
            array('id' => '75','province_id' => '5','name' => 'Barinas','capital' => '1'),
            array('id' => '76','province_id' => '5','name' => 'Barinitas','capital' => '0'),
            array('id' => '77','province_id' => '5','name' => 'Barrancas','capital' => '0'),
            array('id' => '78','province_id' => '5','name' => 'Calderas','capital' => '0'),
            array('id' => '79','province_id' => '5','name' => 'Capitanejo','capital' => '0'),
            array('id' => '80','province_id' => '5','name' => 'Ciudad Bolivia','capital' => '0'),
            array('id' => '81','province_id' => '5','name' => 'El Cantón','capital' => '0'),
            array('id' => '82','province_id' => '5','name' => 'Las Veguitas','capital' => '0'),
            array('id' => '83','province_id' => '5','name' => 'Libertad de Barinas','capital' => '0'),
            array('id' => '84','province_id' => '5','name' => 'Sabaneta','capital' => '0'),
            array('id' => '85','province_id' => '5','name' => 'Santa Bárbara de Barinas','capital' => '0'),
            array('id' => '86','province_id' => '5','name' => 'Socopó','capital' => '0'),
            array('id' => '87','province_id' => '6','name' => 'Caicara del Orinoco','capital' => '0'),
            array('id' => '88','province_id' => '6','name' => 'Canaima','capital' => '0'),
            array('id' => '89','province_id' => '6','name' => 'Ciudad Bolívar','capital' => '1'),
            array('id' => '90','province_id' => '6','name' => 'Ciudad Piar','capital' => '0'),
            array('id' => '91','province_id' => '6','name' => 'El Callao','capital' => '0'),
            array('id' => '92','province_id' => '6','name' => 'El Dorado','capital' => '0'),
            array('id' => '93','province_id' => '6','name' => 'El Manteco','capital' => '0'),
            array('id' => '94','province_id' => '6','name' => 'El Palmar','capital' => '0'),
            array('id' => '95','province_id' => '6','name' => 'El Pao','capital' => '0'),
            array('id' => '96','province_id' => '6','name' => 'Guasipati','capital' => '0'),
            array('id' => '97','province_id' => '6','name' => 'Guri','capital' => '0'),
            array('id' => '98','province_id' => '6','name' => 'La Paragua','capital' => '0'),
            array('id' => '99','province_id' => '6','name' => 'Matanzas','capital' => '0'),
            array('id' => '100','province_id' => '6','name' => 'Puerto Ordaz','capital' => '0'),
            array('id' => '101','province_id' => '6','name' => 'San Félix','capital' => '0'),
            array('id' => '102','province_id' => '6','name' => 'Santa Elena de Uairén','capital' => '0'),
            array('id' => '103','province_id' => '6','name' => 'Tumeremo','capital' => '0'),
            array('id' => '104','province_id' => '6','name' => 'Unare','capital' => '0'),
            array('id' => '105','province_id' => '6','name' => 'Upata','capital' => '0'),
            array('id' => '106','province_id' => '7','name' => 'Bejuma','capital' => '0'),
            array('id' => '107','province_id' => '7','name' => 'Belén','capital' => '0'),
            array('id' => '108','province_id' => '7','name' => 'Campo de Carabobo','capital' => '0'),
            array('id' => '109','province_id' => '7','name' => 'Canoabo','capital' => '0'),
            array('id' => '110','province_id' => '7','name' => 'Central Tacarigua','capital' => '0'),
            array('id' => '111','province_id' => '7','name' => 'Chirgua','capital' => '0'),
            array('id' => '112','province_id' => '7','name' => 'Ciudad Alianza','capital' => '0'),
            array('id' => '113','province_id' => '7','name' => 'El Palito','capital' => '0'),
            array('id' => '114','province_id' => '7','name' => 'Guacara','capital' => '0'),
            array('id' => '115','province_id' => '7','name' => 'Guigue','capital' => '0'),
            array('id' => '116','province_id' => '7','name' => 'Las Trincheras','capital' => '0'),
            array('id' => '117','province_id' => '7','name' => 'Los Guayos','capital' => '0'),
            array('id' => '118','province_id' => '7','name' => 'Mariara','capital' => '0'),
            array('id' => '119','province_id' => '7','name' => 'Miranda','capital' => '0'),
            array('id' => '120','province_id' => '7','name' => 'Montalbán','capital' => '0'),
            array('id' => '121','province_id' => '7','name' => 'Morón','capital' => '0'),
            array('id' => '122','province_id' => '7','name' => 'Naguanagua','capital' => '0'),
            array('id' => '123','province_id' => '7','name' => 'Puerto Cabello','capital' => '0'),
            array('id' => '124','province_id' => '7','name' => 'San Joaquín','capital' => '0'),
            array('id' => '125','province_id' => '7','name' => 'Tocuyito','capital' => '0'),
            array('id' => '126','province_id' => '7','name' => 'Urama','capital' => '0'),
            array('id' => '127','province_id' => '7','name' => 'Valencia','capital' => '1'),
            array('id' => '128','province_id' => '7','name' => 'Vigirimita','capital' => '0'),
            array('id' => '129','province_id' => '8','name' => 'Aguirre','capital' => '0'),
            array('id' => '130','province_id' => '8','name' => 'Apartaderos Cojedes','capital' => '0'),
            array('id' => '131','province_id' => '8','name' => 'Arismendi','capital' => '0'),
            array('id' => '132','province_id' => '8','name' => 'Camuriquito','capital' => '0'),
            array('id' => '133','province_id' => '8','name' => 'El Baúl','capital' => '0'),
            array('id' => '134','province_id' => '8','name' => 'El Limón','capital' => '0'),
            array('id' => '135','province_id' => '8','name' => 'El Pao Cojedes','capital' => '0'),
            array('id' => '136','province_id' => '8','name' => 'El Socorro','capital' => '0'),
            array('id' => '137','province_id' => '8','name' => 'La Aguadita','capital' => '0'),
            array('id' => '138','province_id' => '8','name' => 'Las Vegas','capital' => '0'),
            array('id' => '139','province_id' => '8','name' => 'Libertad de Cojedes','capital' => '0'),
            array('id' => '140','province_id' => '8','name' => 'Mapuey','capital' => '0'),
            array('id' => '141','province_id' => '8','name' => 'Piñedo','capital' => '0'),
            array('id' => '142','province_id' => '8','name' => 'Samancito','capital' => '0'),
            array('id' => '143','province_id' => '8','name' => 'San Carlos','capital' => '1'),
            array('id' => '144','province_id' => '8','name' => 'Sucre','capital' => '0'),
            array('id' => '145','province_id' => '8','name' => 'Tinaco','capital' => '0'),
            array('id' => '146','province_id' => '8','name' => 'Tinaquillo','capital' => '0'),
            array('id' => '147','province_id' => '8','name' => 'Vallecito','capital' => '0'),
            array('id' => '148','province_id' => '9','name' => 'Tucupita','capital' => '1'),
            array('id' => '149','province_id' => '24','name' => 'Caracas','capital' => '1'),
            array('id' => '150','province_id' => '24','name' => 'El Junquito','capital' => '0'),
            array('id' => '151','province_id' => '10','name' => 'Adícora','capital' => '0'),
            array('id' => '152','province_id' => '10','name' => 'Boca de Aroa','capital' => '0'),
            array('id' => '153','province_id' => '10','name' => 'Cabure','capital' => '0'),
            array('id' => '154','province_id' => '10','name' => 'Capadare','capital' => '0'),
            array('id' => '155','province_id' => '10','name' => 'Capatárida','capital' => '0'),
            array('id' => '156','province_id' => '10','name' => 'Chichiriviche','capital' => '0'),
            array('id' => '157','province_id' => '10','name' => 'Churuguara','capital' => '0'),
            array('id' => '158','province_id' => '10','name' => 'Coro','capital' => '1'),
            array('id' => '159','province_id' => '10','name' => 'Cumarebo','capital' => '0'),
            array('id' => '160','province_id' => '10','name' => 'Dabajuro','capital' => '0'),
            array('id' => '161','province_id' => '10','name' => 'Judibana','capital' => '0'),
            array('id' => '162','province_id' => '10','name' => 'La Cruz de Taratara','capital' => '0'),
            array('id' => '163','province_id' => '10','name' => 'La Vela de Coro','capital' => '0'),
            array('id' => '164','province_id' => '10','name' => 'Los Taques','capital' => '0'),
            array('id' => '165','province_id' => '10','name' => 'Maparari','capital' => '0'),
            array('id' => '166','province_id' => '10','name' => 'Mene de Mauroa','capital' => '0'),
            array('id' => '167','province_id' => '10','name' => 'Mirimire','capital' => '0'),
            array('id' => '168','province_id' => '10','name' => 'Pedregal','capital' => '0'),
            array('id' => '169','province_id' => '10','name' => 'Píritu Falcón','capital' => '0'),
            array('id' => '170','province_id' => '10','name' => 'Pueblo Nuevo Falcón','capital' => '0'),
            array('id' => '171','province_id' => '10','name' => 'Puerto Cumarebo','capital' => '0'),
            array('id' => '172','province_id' => '10','name' => 'Punta Cardón','capital' => '0'),
            array('id' => '173','province_id' => '10','name' => 'Punto Fijo','capital' => '0'),
            array('id' => '174','province_id' => '10','name' => 'San Juan de Los Cayos','capital' => '0'),
            array('id' => '175','province_id' => '10','name' => 'San Luis','capital' => '0'),
            array('id' => '176','province_id' => '10','name' => 'Santa Ana Falcón','capital' => '0'),
            array('id' => '177','province_id' => '10','name' => 'Santa Cruz De Bucaral','capital' => '0'),
            array('id' => '178','province_id' => '10','name' => 'Tocopero','capital' => '0'),
            array('id' => '179','province_id' => '10','name' => 'Tocuyo de La Costa','capital' => '0'),
            array('id' => '180','province_id' => '10','name' => 'Tucacas','capital' => '0'),
            array('id' => '181','province_id' => '10','name' => 'Yaracal','capital' => '0'),
            array('id' => '182','province_id' => '11','name' => 'Altagracia de Orituco','capital' => '0'),
            array('id' => '183','province_id' => '11','name' => 'Cabruta','capital' => '0'),
            array('id' => '184','province_id' => '11','name' => 'Calabozo','capital' => '0'),
            array('id' => '185','province_id' => '11','name' => 'Camaguán','capital' => '0'),
            array('id' => '196','province_id' => '11','name' => 'Chaguaramas Guárico','capital' => '0'),
            array('id' => '197','province_id' => '11','name' => 'El Socorro','capital' => '0'),
            array('id' => '198','province_id' => '11','name' => 'El Sombrero','capital' => '0'),
            array('id' => '199','province_id' => '11','name' => 'Las Mercedes de Los Llanos','capital' => '0'),
            array('id' => '200','province_id' => '11','name' => 'Lezama','capital' => '0'),
            array('id' => '201','province_id' => '11','name' => 'Onoto','capital' => '0'),
            array('id' => '202','province_id' => '11','name' => 'Ortíz','capital' => '0'),
            array('id' => '203','province_id' => '11','name' => 'San José de Guaribe','capital' => '0'),
            array('id' => '204','province_id' => '11','name' => 'San Juan de Los Morros','capital' => '1'),
            array('id' => '205','province_id' => '11','name' => 'San Rafael de Laya','capital' => '0'),
            array('id' => '206','province_id' => '11','name' => 'Santa María de Ipire','capital' => '0'),
            array('id' => '207','province_id' => '11','name' => 'Tucupido','capital' => '0'),
            array('id' => '208','province_id' => '11','name' => 'Valle de La Pascua','capital' => '0'),
            array('id' => '209','province_id' => '11','name' => 'Zaraza','capital' => '0'),
            array('id' => '210','province_id' => '12','name' => 'Aguada Grande','capital' => '0'),
            array('id' => '211','province_id' => '12','name' => 'Atarigua','capital' => '0'),
            array('id' => '212','province_id' => '12','name' => 'Barquisimeto','capital' => '1'),
            array('id' => '213','province_id' => '12','name' => 'Bobare','capital' => '0'),
            array('id' => '214','province_id' => '12','name' => 'Cabudare','capital' => '0'),
            array('id' => '215','province_id' => '12','name' => 'Carora','capital' => '0'),
            array('id' => '216','province_id' => '12','name' => 'Cubiro','capital' => '0'),
            array('id' => '217','province_id' => '12','name' => 'Cují','capital' => '0'),
            array('id' => '218','province_id' => '12','name' => 'Duaca','capital' => '0'),
            array('id' => '219','province_id' => '12','name' => 'El Manzano','capital' => '0'),
            array('id' => '220','province_id' => '12','name' => 'El Tocuyo','capital' => '0'),
            array('id' => '221','province_id' => '12','name' => 'Guaríco','capital' => '0'),
            array('id' => '222','province_id' => '12','name' => 'Humocaro Alto','capital' => '0'),
            array('id' => '223','province_id' => '12','name' => 'Humocaro Bajo','capital' => '0'),
            array('id' => '224','province_id' => '12','name' => 'La Miel','capital' => '0'),
            array('id' => '225','province_id' => '12','name' => 'Moroturo','capital' => '0'),
            array('id' => '226','province_id' => '12','name' => 'Quíbor','capital' => '0'),
            array('id' => '227','province_id' => '12','name' => 'Río Claro','capital' => '0'),
            array('id' => '228','province_id' => '12','name' => 'Sanare','capital' => '0'),
            array('id' => '229','province_id' => '12','name' => 'Santa Inés','capital' => '0'),
            array('id' => '230','province_id' => '12','name' => 'Sarare','capital' => '0'),
            array('id' => '231','province_id' => '12','name' => 'Siquisique','capital' => '0'),
            array('id' => '232','province_id' => '12','name' => 'Tintorero','capital' => '0'),
            array('id' => '233','province_id' => '13','name' => 'Apartaderos Mérida','capital' => '0'),
            array('id' => '234','province_id' => '13','name' => 'Arapuey','capital' => '0'),
            array('id' => '235','province_id' => '13','name' => 'Bailadores','capital' => '0'),
            array('id' => '236','province_id' => '13','name' => 'Caja Seca','capital' => '0'),
            array('id' => '237','province_id' => '13','name' => 'Canaguá','capital' => '0'),
            array('id' => '238','province_id' => '13','name' => 'Chachopo','capital' => '0'),
            array('id' => '239','province_id' => '13','name' => 'Chiguara','capital' => '0'),
            array('id' => '240','province_id' => '13','name' => 'Ejido','capital' => '0'),
            array('id' => '241','province_id' => '13','name' => 'El Vigía','capital' => '0'),
            array('id' => '242','province_id' => '13','name' => 'La Azulita','capital' => '0'),
            array('id' => '243','province_id' => '13','name' => 'La Playa','capital' => '0'),
            array('id' => '244','province_id' => '13','name' => 'Lagunillas Mérida','capital' => '0'),
            array('id' => '245','province_id' => '13','name' => 'Mérida','capital' => '1'),
            array('id' => '246','province_id' => '13','name' => 'Mesa de Bolívar','capital' => '0'),
            array('id' => '247','province_id' => '13','name' => 'Mucuchíes','capital' => '0'),
            array('id' => '248','province_id' => '13','name' => 'Mucujepe','capital' => '0'),
            array('id' => '249','province_id' => '13','name' => 'Mucuruba','capital' => '0'),
            array('id' => '250','province_id' => '13','name' => 'Nueva Bolivia','capital' => '0'),
            array('id' => '251','province_id' => '13','name' => 'Palmarito','capital' => '0'),
            array('id' => '252','province_id' => '13','name' => 'Pueblo Llano','capital' => '0'),
            array('id' => '253','province_id' => '13','name' => 'Santa Cruz de Mora','capital' => '0'),
            array('id' => '254','province_id' => '13','name' => 'Santa Elena de Arenales','capital' => '0'),
            array('id' => '255','province_id' => '13','name' => 'Santo Domingo','capital' => '0'),
            array('id' => '256','province_id' => '13','name' => 'Tabáy','capital' => '0'),
            array('id' => '257','province_id' => '13','name' => 'Timotes','capital' => '0'),
            array('id' => '258','province_id' => '13','name' => 'Torondoy','capital' => '0'),
            array('id' => '259','province_id' => '13','name' => 'Tovar','capital' => '0'),
            array('id' => '260','province_id' => '13','name' => 'Tucani','capital' => '0'),
            array('id' => '261','province_id' => '13','name' => 'Zea','capital' => '0'),
            array('id' => '262','province_id' => '14','name' => 'Araguita','capital' => '0'),
            array('id' => '263','province_id' => '14','name' => 'Carrizal','capital' => '0'),
            array('id' => '264','province_id' => '14','name' => 'Caucagua','capital' => '0'),
            array('id' => '265','province_id' => '14','name' => 'Chaguaramas Miranda','capital' => '0'),
            array('id' => '266','province_id' => '14','name' => 'Charallave','capital' => '0'),
            array('id' => '267','province_id' => '14','name' => 'Chirimena','capital' => '0'),
            array('id' => '268','province_id' => '14','name' => 'Chuspa','capital' => '0'),
            array('id' => '269','province_id' => '14','name' => 'Cúa','capital' => '0'),
            array('id' => '270','province_id' => '14','name' => 'Cupira','capital' => '0'),
            array('id' => '271','province_id' => '14','name' => 'Curiepe','capital' => '0'),
            array('id' => '272','province_id' => '14','name' => 'El Guapo','capital' => '0'),
            array('id' => '273','province_id' => '14','name' => 'El Jarillo','capital' => '0'),
            array('id' => '274','province_id' => '14','name' => 'Filas de Mariche','capital' => '0'),
            array('id' => '275','province_id' => '14','name' => 'Guarenas','capital' => '0'),
            array('id' => '276','province_id' => '14','name' => 'Guatire','capital' => '0'),
            array('id' => '277','province_id' => '14','name' => 'Higuerote','capital' => '0'),
            array('id' => '278','province_id' => '14','name' => 'Los Anaucos','capital' => '0'),
            array('id' => '279','province_id' => '14','name' => 'Los Teques','capital' => '1'),
            array('id' => '280','province_id' => '14','name' => 'Ocumare del Tuy','capital' => '0'),
            array('id' => '281','province_id' => '14','name' => 'Panaquire','capital' => '0'),
            array('id' => '282','province_id' => '14','name' => 'Paracotos','capital' => '0'),
            array('id' => '283','province_id' => '14','name' => 'Río Chico','capital' => '0'),
            array('id' => '284','province_id' => '14','name' => 'San Antonio de Los Altos','capital' => '0'),
            array('id' => '285','province_id' => '14','name' => 'San Diego de Los Altos','capital' => '0'),
            array('id' => '286','province_id' => '14','name' => 'San Fernando del Guapo','capital' => '0'),
            array('id' => '287','province_id' => '14','name' => 'San Francisco de Yare','capital' => '0'),
            array('id' => '288','province_id' => '14','name' => 'San José de Los Altos','capital' => '0'),
            array('id' => '289','province_id' => '14','name' => 'San José de Río Chico','capital' => '0'),
            array('id' => '290','province_id' => '14','name' => 'San Pedro de Los Altos','capital' => '0'),
            array('id' => '291','province_id' => '14','name' => 'Santa Lucía','capital' => '0'),
            array('id' => '292','province_id' => '14','name' => 'Santa Teresa','capital' => '0'),
            array('id' => '293','province_id' => '14','name' => 'Tacarigua de La Laguna','capital' => '0'),
            array('id' => '294','province_id' => '14','name' => 'Tacarigua de Mamporal','capital' => '0'),
            array('id' => '295','province_id' => '14','name' => 'Tácata','capital' => '0'),
            array('id' => '296','province_id' => '14','name' => 'Turumo','capital' => '0'),
            array('id' => '297','province_id' => '15','name' => 'Aguasay','capital' => '0'),
            array('id' => '298','province_id' => '15','name' => 'Aragua de Maturín','capital' => '0'),
            array('id' => '299','province_id' => '15','name' => 'Barrancas del Orinoco','capital' => '0'),
            array('id' => '300','province_id' => '15','name' => 'Caicara de Maturín','capital' => '0'),
            array('id' => '301','province_id' => '15','name' => 'Caripe','capital' => '0'),
            array('id' => '302','province_id' => '15','name' => 'Caripito','capital' => '0'),
            array('id' => '303','province_id' => '15','name' => 'Chaguaramal','capital' => '0'),
            array('id' => '305','province_id' => '15','name' => 'Chaguaramas Monagas','capital' => '0'),
            array('id' => '307','province_id' => '15','name' => 'El Furrial','capital' => '0'),
            array('id' => '308','province_id' => '15','name' => 'El Tejero','capital' => '0'),
            array('id' => '309','province_id' => '15','name' => 'Jusepín','capital' => '0'),
            array('id' => '310','province_id' => '15','name' => 'La Toscana','capital' => '0'),
            array('id' => '311','province_id' => '15','name' => 'Maturín','capital' => '1'),
            array('id' => '312','province_id' => '15','name' => 'Miraflores','capital' => '0'),
            array('id' => '313','province_id' => '15','name' => 'Punta de Mata','capital' => '0'),
            array('id' => '314','province_id' => '15','name' => 'Quiriquire','capital' => '0'),
            array('id' => '315','province_id' => '15','name' => 'San Antonio de Maturín','capital' => '0'),
            array('id' => '316','province_id' => '15','name' => 'San Vicente Monagas','capital' => '0'),
            array('id' => '317','province_id' => '15','name' => 'Santa Bárbara','capital' => '0'),
            array('id' => '318','province_id' => '15','name' => 'Temblador','capital' => '0'),
            array('id' => '319','province_id' => '15','name' => 'Teresen','capital' => '0'),
            array('id' => '320','province_id' => '15','name' => 'Uracoa','capital' => '0'),
            array('id' => '321','province_id' => '16','name' => 'Altagracia','capital' => '0'),
            array('id' => '322','province_id' => '16','name' => 'Boca de Pozo','capital' => '0'),
            array('id' => '323','province_id' => '16','name' => 'Boca de Río','capital' => '0'),
            array('id' => '324','province_id' => '16','name' => 'El Espinal','capital' => '0'),
            array('id' => '325','province_id' => '16','name' => 'El Valle del Espíritu Santo','capital' => '0'),
            array('id' => '326','province_id' => '16','name' => 'El Yaque','capital' => '0'),
            array('id' => '327','province_id' => '16','name' => 'Juangriego','capital' => '0'),
            array('id' => '328','province_id' => '16','name' => 'La Asunción','capital' => '1'),
            array('id' => '329','province_id' => '16','name' => 'La Guardia','capital' => '0'),
            array('id' => '330','province_id' => '16','name' => 'Pampatar','capital' => '0'),
            array('id' => '331','province_id' => '16','name' => 'Porlamar','capital' => '0'),
            array('id' => '332','province_id' => '16','name' => 'Puerto Fermín','capital' => '0'),
            array('id' => '333','province_id' => '16','name' => 'Punta de Piedras','capital' => '0'),
            array('id' => '334','province_id' => '16','name' => 'San Francisco de Macanao','capital' => '0'),
            array('id' => '335','province_id' => '16','name' => 'San Juan Bautista','capital' => '0'),
            array('id' => '336','province_id' => '16','name' => 'San Pedro de Coche','capital' => '0'),
            array('id' => '337','province_id' => '16','name' => 'Santa Ana de Nueva Esparta','capital' => '0'),
            array('id' => '338','province_id' => '16','name' => 'Villa Rosa','capital' => '0'),
            array('id' => '339','province_id' => '17','name' => 'Acarigua','capital' => '0'),
            array('id' => '340','province_id' => '17','name' => 'Agua Blanca','capital' => '0'),
            array('id' => '341','province_id' => '17','name' => 'Araure','capital' => '0'),
            array('id' => '342','province_id' => '17','name' => 'Biscucuy','capital' => '0'),
            array('id' => '343','province_id' => '17','name' => 'Boconoito','capital' => '0'),
            array('id' => '344','province_id' => '17','name' => 'Campo Elías','capital' => '0'),
            array('id' => '345','province_id' => '17','name' => 'Chabasquén','capital' => '0'),
            array('id' => '346','province_id' => '17','name' => 'Guanare','capital' => '1'),
            array('id' => '347','province_id' => '17','name' => 'Guanarito','capital' => '0'),
            array('id' => '348','province_id' => '17','name' => 'La Aparición','capital' => '0'),
            array('id' => '349','province_id' => '17','name' => 'La Misión','capital' => '0'),
            array('id' => '350','province_id' => '17','name' => 'Mesa de Cavacas','capital' => '0'),
            array('id' => '351','province_id' => '17','name' => 'Ospino','capital' => '0'),
            array('id' => '352','province_id' => '17','name' => 'Papelón','capital' => '0'),
            array('id' => '353','province_id' => '17','name' => 'Payara','capital' => '0'),
            array('id' => '354','province_id' => '17','name' => 'Pimpinela','capital' => '0'),
            array('id' => '355','province_id' => '17','name' => 'Píritu de Portuguesa','capital' => '0'),
            array('id' => '356','province_id' => '17','name' => 'San Rafael de Onoto','capital' => '0'),
            array('id' => '357','province_id' => '17','name' => 'Santa Rosalía','capital' => '0'),
            array('id' => '358','province_id' => '17','name' => 'Turén','capital' => '0'),
            array('id' => '359','province_id' => '18','name' => 'Altos de Sucre','capital' => '0'),
            array('id' => '360','province_id' => '18','name' => 'Araya','capital' => '0'),
            array('id' => '361','province_id' => '18','name' => 'Cariaco','capital' => '0'),
            array('id' => '362','province_id' => '18','name' => 'Carúpano','capital' => '0'),
            array('id' => '363','province_id' => '18','name' => 'Casanay','capital' => '0'),
            array('id' => '364','province_id' => '18','name' => 'Cumaná','capital' => '1'),
            array('id' => '365','province_id' => '18','name' => 'Cumanacoa','capital' => '0'),
            array('id' => '366','province_id' => '18','name' => 'El Morro Puerto Santo','capital' => '0'),
            array('id' => '367','province_id' => '18','name' => 'El Pilar','capital' => '0'),
            array('id' => '368','province_id' => '18','name' => 'El Poblado','capital' => '0'),
            array('id' => '369','province_id' => '18','name' => 'Guaca','capital' => '0'),
            array('id' => '370','province_id' => '18','name' => 'Guiria','capital' => '0'),
            array('id' => '371','province_id' => '18','name' => 'Irapa','capital' => '0'),
            array('id' => '372','province_id' => '18','name' => 'Manicuare','capital' => '0'),
            array('id' => '373','province_id' => '18','name' => 'Mariguitar','capital' => '0'),
            array('id' => '374','province_id' => '18','name' => 'Río Caribe','capital' => '0'),
            array('id' => '375','province_id' => '18','name' => 'San Antonio del Golfo','capital' => '0'),
            array('id' => '376','province_id' => '18','name' => 'San José de Aerocuar','capital' => '0'),
            array('id' => '377','province_id' => '18','name' => 'San Vicente de Sucre','capital' => '0'),
            array('id' => '378','province_id' => '18','name' => 'Santa Fe de Sucre','capital' => '0'),
            array('id' => '379','province_id' => '18','name' => 'Tunapuy','capital' => '0'),
            array('id' => '380','province_id' => '18','name' => 'Yaguaraparo','capital' => '0'),
            array('id' => '381','province_id' => '18','name' => 'Yoco','capital' => '0'),
            array('id' => '382','province_id' => '19','name' => 'Abejales','capital' => '0'),
            array('id' => '383','province_id' => '19','name' => 'Borota','capital' => '0'),
            array('id' => '384','province_id' => '19','name' => 'Bramon','capital' => '0'),
            array('id' => '385','province_id' => '19','name' => 'Capacho','capital' => '0'),
            array('id' => '386','province_id' => '19','name' => 'Colón','capital' => '0'),
            array('id' => '387','province_id' => '19','name' => 'Coloncito','capital' => '0'),
            array('id' => '388','province_id' => '19','name' => 'Cordero','capital' => '0'),
            array('id' => '389','province_id' => '19','name' => 'El Cobre','capital' => '0'),
            array('id' => '390','province_id' => '19','name' => 'El Pinal','capital' => '0'),
            array('id' => '391','province_id' => '19','name' => 'Independencia','capital' => '0'),
            array('id' => '392','province_id' => '19','name' => 'La Fría','capital' => '0'),
            array('id' => '393','province_id' => '19','name' => 'La Grita','capital' => '0'),
            array('id' => '394','province_id' => '19','name' => 'La Pedrera','capital' => '0'),
            array('id' => '395','province_id' => '19','name' => 'La Tendida','capital' => '0'),
            array('id' => '396','province_id' => '19','name' => 'Las Delicias','capital' => '0'),
            array('id' => '397','province_id' => '19','name' => 'Las Hernández','capital' => '0'),
            array('id' => '398','province_id' => '19','name' => 'Lobatera','capital' => '0'),
            array('id' => '399','province_id' => '19','name' => 'Michelena','capital' => '0'),
            array('id' => '400','province_id' => '19','name' => 'Palmira','capital' => '0'),
            array('id' => '401','province_id' => '19','name' => 'Pregonero','capital' => '0'),
            array('id' => '402','province_id' => '19','name' => 'Queniquea','capital' => '0'),
            array('id' => '403','province_id' => '19','name' => 'Rubio','capital' => '0'),
            array('id' => '404','province_id' => '19','name' => 'San Antonio del Tachira','capital' => '0'),
            array('id' => '405','province_id' => '19','name' => 'San Cristobal','capital' => '1'),
            array('id' => '406','province_id' => '19','name' => 'San José de Bolívar','capital' => '0'),
            array('id' => '407','province_id' => '19','name' => 'San Josecito','capital' => '0'),
            array('id' => '408','province_id' => '19','name' => 'San Pedro del Río','capital' => '0'),
            array('id' => '409','province_id' => '19','name' => 'Santa Ana Táchira','capital' => '0'),
            array('id' => '410','province_id' => '19','name' => 'Seboruco','capital' => '0'),
            array('id' => '411','province_id' => '19','name' => 'Táriba','capital' => '0'),
            array('id' => '412','province_id' => '19','name' => 'Umuquena','capital' => '0'),
            array('id' => '413','province_id' => '19','name' => 'Ureña','capital' => '0'),
            array('id' => '414','province_id' => '20','name' => 'Batatal','capital' => '0'),
            array('id' => '415','province_id' => '20','name' => 'Betijoque','capital' => '0'),
            array('id' => '416','province_id' => '20','name' => 'Boconó','capital' => '0'),
            array('id' => '417','province_id' => '20','name' => 'Carache','capital' => '0'),
            array('id' => '418','province_id' => '20','name' => 'Chejende','capital' => '0'),
            array('id' => '419','province_id' => '20','name' => 'Cuicas','capital' => '0'),
            array('id' => '420','province_id' => '20','name' => 'El Dividive','capital' => '0'),
            array('id' => '421','province_id' => '20','name' => 'El Jaguito','capital' => '0'),
            array('id' => '422','province_id' => '20','name' => 'Escuque','capital' => '0'),
            array('id' => '423','province_id' => '20','name' => 'Isnotú','capital' => '0'),
            array('id' => '424','province_id' => '20','name' => 'Jajó','capital' => '0'),
            array('id' => '425','province_id' => '20','name' => 'La Ceiba','capital' => '0'),
            array('id' => '426','province_id' => '20','name' => 'La Concepción de Trujllo','capital' => '0'),
            array('id' => '427','province_id' => '20','name' => 'La Mesa de Esnujaque','capital' => '0'),
            array('id' => '428','province_id' => '20','name' => 'La Puerta','capital' => '0'),
            array('id' => '429','province_id' => '20','name' => 'La Quebrada','capital' => '0'),
            array('id' => '430','province_id' => '20','name' => 'Mendoza Fría','capital' => '0'),
            array('id' => '431','province_id' => '20','name' => 'Meseta de Chimpire','capital' => '0'),
            array('id' => '432','province_id' => '20','name' => 'Monay','capital' => '0'),
            array('id' => '433','province_id' => '20','name' => 'Motatán','capital' => '0'),
            array('id' => '434','province_id' => '20','name' => 'Pampán','capital' => '0'),
            array('id' => '435','province_id' => '20','name' => 'Pampanito','capital' => '0'),
            array('id' => '436','province_id' => '20','name' => 'Sabana de Mendoza','capital' => '0'),
            array('id' => '437','province_id' => '20','name' => 'San Lázaro','capital' => '0'),
            array('id' => '438','province_id' => '20','name' => 'Santa Ana de Trujillo','capital' => '0'),
            array('id' => '439','province_id' => '20','name' => 'Tostós','capital' => '0'),
            array('id' => '440','province_id' => '20','name' => 'Trujillo','capital' => '1'),
            array('id' => '441','province_id' => '20','name' => 'Valera','capital' => '0'),
            array('id' => '442','province_id' => '21','name' => 'Carayaca','capital' => '0'),
            array('id' => '443','province_id' => '21','name' => 'Litoral','capital' => '0'),
            array('id' => '444','province_id' => '25','name' => 'Archipiélago Los Roques','capital' => '0'),
            array('id' => '445','province_id' => '22','name' => 'Aroa','capital' => '0'),
            array('id' => '446','province_id' => '22','name' => 'Boraure','capital' => '0'),
            array('id' => '447','province_id' => '22','name' => 'Campo Elías de Yaracuy','capital' => '0'),
            array('id' => '448','province_id' => '22','name' => 'Chivacoa','capital' => '0'),
            array('id' => '449','province_id' => '22','name' => 'Cocorote','capital' => '0'),
            array('id' => '450','province_id' => '22','name' => 'Farriar','capital' => '0'),
            array('id' => '451','province_id' => '22','name' => 'Guama','capital' => '0'),
            array('id' => '452','province_id' => '22','name' => 'Marín','capital' => '0'),
            array('id' => '453','province_id' => '22','name' => 'Nirgua','capital' => '0'),
            array('id' => '454','province_id' => '22','name' => 'Sabana de Parra','capital' => '0'),
            array('id' => '455','province_id' => '22','name' => 'Salom','capital' => '0'),
            array('id' => '456','province_id' => '22','name' => 'San Felipe','capital' => '1'),
            array('id' => '457','province_id' => '22','name' => 'San Pablo de Yaracuy','capital' => '0'),
            array('id' => '458','province_id' => '22','name' => 'Urachiche','capital' => '0'),
            array('id' => '459','province_id' => '22','name' => 'Yaritagua','capital' => '0'),
            array('id' => '460','province_id' => '22','name' => 'Yumare','capital' => '0'),
            array('id' => '461','province_id' => '23','name' => 'Bachaquero','capital' => '0'),
            array('id' => '462','province_id' => '23','name' => 'Bobures','capital' => '0'),
            array('id' => '463','province_id' => '23','name' => 'Cabimas','capital' => '0'),
            array('id' => '464','province_id' => '23','name' => 'Campo Concepción','capital' => '0'),
            array('id' => '465','province_id' => '23','name' => 'Campo Mara','capital' => '0'),
            array('id' => '466','province_id' => '23','name' => 'Campo Rojo','capital' => '0'),
            array('id' => '467','province_id' => '23','name' => 'Carrasquero','capital' => '0'),
            array('id' => '468','province_id' => '23','name' => 'Casigua','capital' => '0'),
            array('id' => '469','province_id' => '23','name' => 'Chiquinquirá','capital' => '0'),
            array('id' => '470','province_id' => '23','name' => 'Ciudad Ojeda','capital' => '0'),
            array('id' => '471','province_id' => '23','name' => 'El Batey','capital' => '0'),
            array('id' => '472','province_id' => '23','name' => 'El Carmelo','capital' => '0'),
            array('id' => '473','province_id' => '23','name' => 'El Chivo','capital' => '0'),
            array('id' => '474','province_id' => '23','name' => 'El Guayabo','capital' => '0'),
            array('id' => '475','province_id' => '23','name' => 'El Mene','capital' => '0'),
            array('id' => '476','province_id' => '23','name' => 'El Venado','capital' => '0'),
            array('id' => '477','province_id' => '23','name' => 'Encontrados','capital' => '0'),
            array('id' => '478','province_id' => '23','name' => 'Gibraltar','capital' => '0'),
            array('id' => '479','province_id' => '23','name' => 'Isla de Toas','capital' => '0'),
            array('id' => '480','province_id' => '23','name' => 'La Concepción del Zulia','capital' => '0'),
            array('id' => '481','province_id' => '23','name' => 'La Paz','capital' => '0'),
            array('id' => '482','province_id' => '23','name' => 'La Sierrita','capital' => '0'),
            array('id' => '483','province_id' => '23','name' => 'Lagunillas del Zulia','capital' => '0'),
            array('id' => '484','province_id' => '23','name' => 'Las Piedras de Perijá','capital' => '0'),
            array('id' => '485','province_id' => '23','name' => 'Los Cortijos','capital' => '0'),
            array('id' => '486','province_id' => '23','name' => 'Machiques','capital' => '0'),
            array('id' => '487','province_id' => '23','name' => 'Maracaibo','capital' => '1'),
            array('id' => '488','province_id' => '23','name' => 'Mene Grande','capital' => '0'),
            array('id' => '489','province_id' => '23','name' => 'Palmarejo','capital' => '0'),
            array('id' => '490','province_id' => '23','name' => 'Paraguaipoa','capital' => '0'),
            array('id' => '491','province_id' => '23','name' => 'Potrerito','capital' => '0'),
            array('id' => '492','province_id' => '23','name' => 'Pueblo Nuevo del Zulia','capital' => '0'),
            array('id' => '493','province_id' => '23','name' => 'Puertos de Altagracia','capital' => '0'),
            array('id' => '494','province_id' => '23','name' => 'Punta Gorda','capital' => '0'),
            array('id' => '495','province_id' => '23','name' => 'Sabaneta de Palma','capital' => '0'),
            array('id' => '496','province_id' => '23','name' => 'San Francisco','capital' => '0'),
            array('id' => '497','province_id' => '23','name' => 'San José de Perijá','capital' => '0'),
            array('id' => '498','province_id' => '23','name' => 'San Rafael del Moján','capital' => '0'),
            array('id' => '499','province_id' => '23','name' => 'San Timoteo','capital' => '0'),
            array('id' => '500','province_id' => '23','name' => 'Santa Bárbara Del Zulia','capital' => '0'),
            array('id' => '501','province_id' => '23','name' => 'Santa Cruz de Mara','capital' => '0'),
            array('id' => '502','province_id' => '23','name' => 'Santa Cruz del Zulia','capital' => '0'),
            array('id' => '503','province_id' => '23','name' => 'Santa Rita','capital' => '0'),
            array('id' => '504','province_id' => '23','name' => 'Sinamaica','capital' => '0'),
            array('id' => '505','province_id' => '23','name' => 'Tamare','capital' => '0'),
            array('id' => '506','province_id' => '23','name' => 'Tía Juana','capital' => '0'),
            array('id' => '507','province_id' => '23','name' => 'Villa del Rosario','capital' => '0'),
            array('id' => '508','province_id' => '21','name' => 'La Guaira','capital' => '1'),
            array('id' => '509','province_id' => '21','name' => 'Catia La Mar','capital' => '0'),
            array('id' => '510','province_id' => '21','name' => 'Macuto','capital' => '0'),
            array('id' => '511','province_id' => '21','name' => 'Naiguatá','capital' => '0'),
            array('id' => '512','province_id' => '25','name' => 'Archipiélago Los Monjes','capital' => '0'),
            array('id' => '513','province_id' => '25','name' => 'Isla La Tortuga y Cayos adyacentes','capital' => '0'),
            array('id' => '514','province_id' => '25','name' => 'Isla La Sola','capital' => '0'),
            array('id' => '515','province_id' => '25','name' => 'Islas Los Testigos','capital' => '0'),
            array('id' => '516','province_id' => '25','name' => 'Islas Los Frailes','capital' => '0'),
            array('id' => '517','province_id' => '25','name' => 'Isla La Orchila','capital' => '0'),
            array('id' => '518','province_id' => '25','name' => 'Archipiélago Las Aves','capital' => '0'),
            array('id' => '519','province_id' => '25','name' => 'Isla de Aves','capital' => '0'),
            array('id' => '520','province_id' => '25','name' => 'Isla La Blanquilla','capital' => '0'),
            array('id' => '521','province_id' => '25','name' => 'Isla de Patos','capital' => '0'),
            array('id' => '522','province_id' => '25','name' => 'Islas Los Hermanos','capital' => '0')
        );

        foreach ($cities as $city) {
            City::firstOrCreate($city, $city);
        }
    }
}
